---
name: Deploy New App GW
description: Start deploying a new Azure-3.0 App GW by deploying an associated Repo
body:
  - type: markdown
    attributes:
      value: |
        To start deploying an AZ3 App GW, fill out the following values:      

  - type: input
    id: newAppGWName
    attributes:
      description: Name for the new AppGW
      label: This is not the name for the new repo, but rather the AppGW itself.

  - type: input
    id: newAppGwRepoName
    attributes:
      description: This is not the name for the new AppGW, but rather then associated Repo.
      label: New AppGW Repo Name

  - type: input
    id: AdoABNumber
    attributes:
      description: ADO AB User Story
      label: The ADO Board story number will be used by the automation pipeline.

  - type: input
    id: changeTemplateId
    attributes:
      description: Change Template ID
      label: This is Humana's change template id.    

  - type: input
    id: AppServiceID
    attributes:
      description: ServiceNow Application Service ID
      label: This is the app id as shown in ServiceNow.

  - type: input
    id: AppDesc
    attributes:
      label: Application Description
      description: This is the description found in asset.yml

  - type: input
    id: target_env
    attributes:
      label: Environment to deploy new AppGW to
      description: Is it NPE, Perf, or Prod?

  - type: input
    id: resource_group_name
    attributes:
      description: Name of the Azure resource group this AppGW will belong to.
      label: see [What is a resource group](https://learn.microsoft.com/en-us/azure/azure-resource-manager/management/manage-resource-groups-portal#what-is-a-resource-group)

  - type: input
    id: app_gw_location
    attributes:
      description: Region Specification
      label: Which region(s) will this AppGW operate in?

  - type: input
    id: backend_address_pool_name
    attributes:
      description: Back-end Address Pool Name
      label: The name of the Backend Address Pool

  - type: input
    id: backend_address_pool_fqdns
    attributes:
      description: Backend Address Pool FQDN
      label: What is the FQDN of the Backend Address Pool

  - type: input
    id: backend_address_pool_ip_addresses
    attributes:
      description: Backend IP Addresses
      label: List of ip addresses for backend.

  - type: input
    id: backend_http_settings_name
    attributes:
      label: The name of the Backend HTTP Settings Collection.
      

  - type: input
    id: backend_http_settings_cookie_based_affinity
    attributes:
      label: Is Cookie-Based Affinity enabled? Possible values are Enabled and Disabled
      

  - type: input
    id: backend_http_settings_port
    attributes:
      description: The port which should be used for this Backend HTTP Settings Collection.
      label: Backend HTTP Settings Port

  - type: input
    id: backend_http_settings_protocol
    attributes:
      description: The Protocol which should be used. Possible values are Http and Https
      label: Backend HTTP Settings Protocol

  - type: input
    id: frontend_ip_configuration_name
    attributes:
      description: The name of the Frontend IP Configuration.
      label: Frontend IP Configuration Name

  - type: input
    id: frontend_port_name
    attributes:
      description: The name of the Frontend Port.
      label: Frontend Port Name

  - type: input
    id: frontend_port_number
    attributes:
      description: The port used for this Frontend Port.
      label: Frontend Port Number

  - type: input
    id: gateway_ip_configuration_name
    attributes:
      description: The Name of this Gateway IP Configuration.
      label: Gateway IP Configuration Name

  - type: input
    id: gateway_ip_configuration_subnet_id
    attributes:
      description: The ID of the Subnet which the Application Gateway should be connected to.
      label: Gateway IP Config Subnet ID

  - type: input
    id: http_listener_name
    attributes:
      description:  The Name of the HTTP Listener.
      label: HTTP Lister Name

  - type: input
    id: http_listener_frontend_ip_configuration_name
    attributes:
      description: The Name of the Frontend IP Configuration used for this HTTP Listener.
      label: IP Config Name

  - type: input
    id: http_listener_frontend_port_name
    attributes:
      description: The Name of the Frontend Port use for this HTTP Listener.
      label: Frontend Port Name

  - type: input
    id: request_routing_rule_name
    attributes:
      description: The Name of this Request Routing Rule.
      label: Request Routing Rule Name

  - type: input
    id: request_routing_rule_type
    attributes:
      description: The Type of Routing that should be used for this Rule. Possible values are Basic and PathBasedRouting.
      label: Request Routing Rule Type

  - type: input
    id: sku_name
    attributes:
      description: The Name of the SKU to use for this Application Gateway. Possible values are Basic, Standard_v2, and WAF_v2.
      label: SKU Name

  - type: input
    id: sku_tier
    attributes:
      description: The Tier of the SKU to use for this Application Gateway. Possible values are Basic, Standard_v2, and WAF_v2.
      label: SKU Tier
